# fly.toml file generated for old-sunset-8207 on 2022-12-27T11:11:36+01:00

app = "old-sunset-8207"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/hellofly:latest"

[env]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"] // highlight-line
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
