name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 12 * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify URL with deployment
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://little-fire-716.fly.dev/
          max-attemps: 3
          retry-delay: 5s
